### ISSUE TITLE
Hex and rgb values according to standards

### ISSUE THREAD

**Issue by Sandstedt** [SpycerLviv/CoronaSDK-RGB-percentage#1]
Nice script, but would be good to format the hex and rgb values according to web standards.

Ex hex is always written `#ff00ff` not `ff00ff`. So in `convert.lua:4`, your could instead write:

```
local hash,redColor,greenColor,blueColor=hex:match('(.)(..)(..)(..)')
```

And `rgb` value doesn't take alpha, but `rgba` does. But the alpha goes from 0 to 1 instead of 0 to 100, so on row 18-21:

```
if alpha == nil then
  return redColor, greenColor, blueColor
end
return redColor, greenColor, blueColor, alpha
```

Can write a PR if you want :)

**Comment by dmoa** [comment]
Agreed, there should be an option for this though

**Comment by andrewyavors** [comment]
Thank you, fixed!
